export interface TradeReceipt {
  receiptVersion: string;
  mode: "simulation" | "mainnet";
  status: "simulated" | "draft" | "signed" | "pending" | "confirmed" | "failed";
  network: string;
  chainId: number;
  rpc: string;
  receiptId: string;
  timestamp: string;
  blockNumber: number;
  trader: string;
  pair: string;
  baseSymbol: string;
  quoteSymbol: string;
  baseContract: string;
  quoteContract: string;
  side: "buy" | "sell";
  amountUsd: number;
  amount: number;
  effectivePrice: number;
  quotedPrice: number;
  estimatedReceived: number;
  minReceived: number;
  priceImpactPct: number;
  slippageBps: number;
  gasToken: string;
  gasUsd: number | string;
  mandateId: string;
  signature: string;
  transactionHash?: string | null;
  executionReceiptHash?: string | null;
  actualAmountInRaw?: string | null;
  actualAmountOutRaw?: string | null;
  actualReceived?: number | null;
  integrityDigest: string;
  onchainAnchored?: boolean;
  anchorTx?: string;
  anchoredAt?: number;
}
