import React from "react";
import {
  Activity,
  Anchor,
  Calculator,
  Fingerprint,
  Clock,
  Radio,
  Lightbulb,
  Sigma,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  Clipboard,
  Code,
  Coins,
  Copy,
  Download,
  ExternalLink,
  Eye,
  FileCheck,
  FileJson,
  FileText,
  FlaskConical,
  Fuel,
  Gauge,
  Globe,
  History,
  Info,
  Landmark,
  Layers,
  List,
  LoaderCircle,
  Lock,
  LogOut,
  Menu,
  Moon,
  Pause,
  Play,
  Plus,
  PlusCircle,
  RefreshCw,
  Search,
  Settings2,
  ShieldCheck,
  ShieldX,
  SlidersHorizontal,
  Sparkles,
  Sun,
  TrendingDown,
  TrendingUp,
  Wallet,
  X,
  Zap,
  ArrowLeftRight,
  CandlestickChart,
  Circle,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const icons: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  savings: Coins,
  candlestick_chart: CandlestickChart,
  query_stats: BarChart3,
  psychology: Bot,
  receipt_long: FileText,
  verified_user: ShieldCheck,
  science: FlaskConical,
  search: Search,
  play_circle: Play,
  play_arrow: Play,
  pause: Pause,
  arrow_forward: ArrowRight,
  arrow_back: ChevronLeft,
  north_east: ArrowUpRight,
  local_gas_station: Fuel,
  logout: LogOut,
  light_mode: Sun,
  dark_mode: Moon,
  menu: Menu,
  close: X,
  sync: RefreshCw,
  refresh: RefreshCw,
  verified: ShieldCheck,
  open_in_new: ExternalLink,
  tune: SlidersHorizontal,
  check: Check,
  check_circle: CircleCheck,
  done_all: CheckCheck,
  error: CircleAlert,
  warning: CircleAlert,
  info: Info,
  help: CircleHelp,
  add: Plus,
  add_circle: PlusCircle,
  draw: FileCheck,
  swap_calls: ArrowLeftRight,
  swap_horiz: ArrowLeftRight,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  bolt: Zap,
  gavel: Landmark,
  unfold_more: ChevronDown,
  expand_more: ChevronDown,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  visibility: Eye,
  description: FileText,
  content_copy: Copy,
  download: Download,
  lock: Lock,
  lock_open: Lock,
  code: Code,
  terminal: Code,
  shield: ShieldCheck,
  security: ShieldCheck,
  block: ShieldX,
  dangerous: ShieldX,
  history: History,
  auto_awesome: Sparkles,
  smart_toy: Bot,
  monitoring: Activity,
  show_chart: Activity,
  speed: Gauge,
  public: Globe,
  layers: Layers,
  checklist: List,
  format_list_bulleted: List,
  notifications: Bell,
  settings: Settings2,
  data_object: FileJson,
  assignment: Clipboard,
  menu_book: BookOpen,
  hourglass_empty: LoaderCircle,
  hourglass_top: LoaderCircle,
  pending: LoaderCircle,
  anchor: Anchor,
  calculate: Calculator,
  fingerprint: Fingerprint,
  functions: Sigma,
  payments: Coins,
  schedule: Clock,
  sensors: Radio,
  tips_and_updates: Lightbulb,
  travel_explore: Globe,
  circle: Circle,
};

export const Icon: React.FC<{ name: string; className?: string }> = ({
  name,
  className = "",
}) => {
  const Glyph = icons[name.trim()] || Circle;
  return (
    <Glyph
      aria-hidden="true"
      focusable="false"
      className={`app-icon ${className}`}
      strokeWidth={1.7}
    />
  );
};
